#' Color map of dynamic simulation output
#'
#' Plots the output of a dynamic 1D diagenetic model.
#'
#' @param name Name of the item (i.e. variable or process rate) to be plotted.
#' @param dyn Matrix generated by a call to \code{deSolve::ode}.
#' @param gr The grid used to create \code{dyn}. Must have been created by a
#'   call to \code{\link{makeGrid}}.
#' @param xlab Label for the time axis (x).
#' @param ylab Label for the depth axis (y).
#' @param timeconv A function applied to the first column of \code{dyn} in order
#'   to convert numeric times to values of class \code{POSIXct}.
#' @param ... Further arguments to be passed to \code{fields::image.plot}. It is
#'   often useful to pass \code{legend.mar} at least.
#'
#' @return \code{NULL}
#'
#' @note The function calls \code{fields::image.plot} which is possibly
#'   incompatible with the \code{layout} to arrange multiple plots.
#'
#' @author David Kneis \email{david.kneis@@tu-dresden.de}
#'
#' @export
#'
#' @examples
#' gr= makeGrid(dz0=0.01, dzMax=0.02, zMax=0.2, beta=1)
#' times= 0:10
#' values= matrix(runif(length(times)*nrow(gr)), nrow=length(times))
#' dyn= cbind(times, values)
#' colnames(dyn)= c("time", paste("X",1:nrow(gr),sep="."))
#' plot3d("X", dyn, gr)

plot3d= function(name, dyn, gr, xlab="time", ylab="depth",
  timeconv=function(x){ISOdatetime(1970,1,1,0,0,0)+x}, ...) {
  m= dyn[,paste(name,1:nrow(gr),sep=".")]
  m= m[,ncol(m):1]
  t= timeconv(dyn[,"time"])
  d= c(-gr$zLw[nrow(gr):1], 0)
  if (min(m) != max(m)) {
    fields::image.plot(x=t, y=d, z=m, xlab=xlab, ylab=ylab, ...)
  } else {
    plot(x=range(t), y=range(d), type="n", bty="n", xlab=xlab, ylab=ylab)
    legend("center", bty="n", legend=paste0("const at ",min(m)))
  }
  return(invisible(NULL))
}

